export const FETCH_TRIPS_REQUEST = "FETCH_TRIPS_REQUEST";
export const FETCH_TRIPS_SUCCESS = "FETCH_TRIPS_SUCCESS";
export const FETCH_TRIPS_FAILURE = "FETCH_TRIPS_FAILURE";
export const UPDATE_TRAVEL_DATE = "UPDATE_TRAVEL_DATE";
export const UPDATE_DESTINATION_CITY = "UPDATE_DESTINATION_CITY";
export const UPDATE_JOURNEY_DETAILS = "UPDATE_JOURNEY_DETAILS";
export const UPDATE_SOURCE_CITY = "UPDATE_SOURCE_CITY";
